# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1025a0469289b7a1eb903f7f89e164b1dcccfff365fb5a0beea569cccbd0fa54ebd09972b789378d8d6a13ef4bfec53c3bcd96674f4101550d1c5e12d4e37e75

test:
  secret_key_base: 6c16a1631c06edeecb3c9c95839e5035b123dc1ecc5dc885782c17f991ca98d532d221cf83f32f5ed22e183b6335a7f1b34b1bf00424a094605112097ced640e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
